FROM ubuntu:focal
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /hicn-build

COPY Makefile versions.cmake ./
COPY scripts scripts/

RUN apt update && apt-get install -y \
  make \
  sudo \
  curl \
  valgrind \
  git

RUN make deps debug-tools

ENV DEBIAN_FRONTEND=
