#ifndef HICNCTRL_MODULE_HICNLIGHT_LISTENER_H
#define HICNCTRL_MODULE_HICNLIGHT_LISTENER_H

#include "../../module.h"

DECLARE_MODULE_OBJECT_OPS_H(hicnlight, listener);

#endif /* HICNCTRL_MODULE_HICNLIGHT_LISTENER_H */
