#ifndef HICNCTRL_MODULE_HICNLIGHT_STRATEGY_H
#define HICNCTRL_MODULE_HICNLIGHT_STRATEGY_H

#include "../../module.h"

DECLARE_MODULE_OBJECT_OPS_H(hicnlight, strategy);

#endif /* HICNCTRL_MODULE_HICNLIGHT_STRATEGY_H */
