#ifndef HICNCTRL_MODULE_HICNLIGHT_SUBSCRIPTION_H
#define HICNCTRL_MODULE_HICNLIGHT_SUBSCRIPTION_H

#include "../../module.h"

DECLARE_MODULE_OBJECT_OPS_H(hicnlight, subscription);

#endif /* HICNCTRL_MODULE_HICNLIGHT_SUBSCRIPTION_H */
