version: "3"
services:
  vpp_client:
    build: .
    working_dir: /home/ubuntu/host-stack
    privileged: true
    container_name: vpp_client
    hostname: client
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/ubuntu/host-stack:/home/ubuntu/host-stack
      - /var/run/vpp:/var/run/vpp
      - /lib/modules:/lib/modules
    environment:
      - STARTUP_CONF=${PWD}/startup-client.conf
      - VCL_CFG=/home/ubuntu/host-stack/hicn/hicn-plugin/testbed/vcl.conf
    entrypoint: [tail, -f, /dev/null]
  vpp_server:
    build: .
    working_dir: /home/ubuntu/host-stack
    privileged: true
    container_name: vpp_server
    hostname: server
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/ubuntu/host-stack:/home/ubuntu/host-stack
      - /var/run/vpp:/var/run/vpp
      - /lib/modules:/lib/modules
    environment:
      - STARTUP_CONF=${PWD}/startup-server.conf
      - VCL_CFG=/home/ubuntu/host-stack/hicn/hicn-plugin/testbed/vcl.conf
    entrypoint: [tail, -f, /dev/null]
