#!/bin/bash

if [ -e /etc/vpp/startup.conf ]; then
    RESULTS=$(sed -n '/hicn[ ]*{/p' /etc/vpp/startup.conf | wc -l)
    if [[ $RESULTS = 0 ]]; then
        printf '\n hicn {
            ## Set PIT size. Default is 131 072 entries
            # pit-size 500000
            #
            ## Set CS size. Default is 4096
            # cs-size 50000
            #
            ## Set maximum PIT entries lifetime in milliseconds. Assigned to a PIT entry in case an interest carries a bigger lifetime
            # pit-lifetime-max 20
            #
            ## Percentage of CS to reserve for application producer faces
            # cs-reserved-app 20\n}' >> /etc/vpp/startup.conf
    fi;
fi;
ln -s /usr/lib64/vpp_plugins/hicn_plugin.so /usr/lib/vpp_plugins/hicn_plugin.so