FROM ubuntu:focal
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workspace
COPY Makefile versions.cmake ./
COPY scripts scripts/

RUN apt update && apt-get install -y \
  make \
  sudo \
  curl \
  git

RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

RUN apt update && apt-get install -y \
  nodejs \
  unzip

RUN make deps debug-tools